### ISSUE TITLE
Libusb error

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [valdivj/Azure-for-Kinect-Jetson-nano#4]
Hi 
Thanks for the instructions you provided. It was really helpful to get started with the kinect Azure with Jetson Nano.

But I have the following messages when I try to run the Kinect Azure. There were two cases

1. While device is connected but the K4aviewer was not able to recognize the device .

`[2020-08-12 23:31:52.906] [error] [t=9030] ../src/usbcommand/usbcommand.c (748): usb_cmd_io(). Error calling libusb_bulk_transfer for initial tx, result:LIBUSB_ERROR_TIMEOUT
[2020-08-12 23:31:52.906] [error] [t=9030] ../src/usbcommand/usbcommand.c (805): usb_cmd_io(usbcmd_handle, cmd, p_cmd_data, cmd_data_size, p_data, data_size, NULL, 0, bytes_read, &cmd_status) returned failure in usb_cmd_read()
[2020-08-12 23:31:52.906] [error] [t=9030] ../src/depth_mcu/depth_mcu.c (412): usb_cmd_read( depthmcu->usb_cmd, DEV_CMD_DEPTH_READ_CALIBRATION_DATA, NULL, 0, (uint8_t *)json, json_size, bytes_read) returned failure in depthmcu_get_extrinsic_calibration()`

2.  I tried to unplug the Kinect Azure device and reconnect it again. This worked. I was able to launch K4aViewer. But had the following error. 
`libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12
`

Thanks for you time.
P.S Furthermore, I am trying to use openpose to find the pose of the human. While I am doing this, the openpose is not able to detect the camera. If you by any chance know how to fix this. It would be really helpful.

**Comment by valdivj** [comment]
I have come across that issue also. I haven't figured out why it occasionally does that. I usually just try reinstalling everything

**Comment by AswinkarthikeyenAK** [comment]
Hi @valdivj ,
I was recommended a solution by @qm13, please refer this https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/485.


Do you by any chance have tried installing the kinect azure body tracking sdk? If so, it would be really great to know how it can be done in jetson nano.

Thanks

**Comment by mariusbrataas** [comment]
@AswinkarthikeyenAK Did you figure this out yet? I'm having the exact same issue. Could you specify how [microsoft/Azure-Konect-Sensor-SDK#485](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/485) helped you?

**Comment by AswinkarthikeyenAK** [comment]
@mariusbrataas ,
I increased the usbfs_memory_mb to 1024. The steps to do this are provided there.
Increasing this helped me resolve this error `libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=12 `
